- name: Set up ssh password
  hosts: vulnerable
  tasks:
    - name: Set up vulnerable password for ssh
      ansible.builtin.shell: |
              sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
              curl https://raw.githubusercontent.com/defboxio/ssh-bruteforce/main/configs/sshd_config > /etc/ssh/sshd_config
              sudo service ssh restart
              useradd -ou 0 -g 0 -m keeton
              echo "keeton:Qm8Aokcvl9NHzO1XJRs1KYhTkTq0SmZf" | chpasswd
      ignore_errors: yes